##Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
data.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [6]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

##Separate Features and Target


In [7]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

##Splitting Data into Train and Test sets

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

##Standardization

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
t_train = y_train.reshape(len(y_train), 1)
t_test = y_test.reshape(len(y_test), 1)

In [12]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [13]:
xt_train = x_sc.fit_transform(x_train)
yt_train = y_sc.fit_transform(t_train)

In [14]:
xt_test = x_sc.transform(x_test)
yt_test = y_sc.transform(t_test)

In [15]:
xt_train

array([[-0.18593394,  1.06765784, -0.25397745, ..., -0.46652179,
        -0.69141909, -0.85374086],
       [-1.40190657,  0.13111626, -0.87458659, ...,  1.37123846,
         0.6016256 ,  0.73957166],
       [ 1.20374908,  0.13111626, -0.20226003, ..., -0.59779038,
        -0.1036715 , -0.10394673],
       ...,
       [ 0.16148682, -0.03916402,  0.57350139, ..., -0.72905897,
        -0.80896861, -0.94746513],
       [ 1.66697675,  0.81223741,  1.45269766, ..., -0.92596186,
         0.3077518 , -0.85374086],
       [-0.41754777, -1.23112603,  0.36663168, ..., -0.59779038,
        -0.3975453 ,  1.95798712]])

In [16]:
yt_train

array([[ 0.4450682 ],
       [ 0.4450682 ],
       [ 0.4450682 ],
       ...,
       [-0.78973056],
       [ 0.4450682 ],
       [ 1.67986696]])

##Train on different algorithms


In [17]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [18]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [19]:
x_pol = PolynomialFeatures(degree=2)
x_pol = x_pol.fit_transform(xt_train)

In [20]:
temp = PolynomialFeatures(degree=2)
temp = temp.fit_transform(xt_test)

In [21]:
r_reg.fit(xt_train, yt_train)
l_reg.fit(xt_train, yt_train)
d_reg.fit(xt_train, yt_train)
s_reg.fit(xt_train, yt_train)
p_reg.fit(x_pol, yt_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
r_pred = r_reg.predict(xt_test)
l_pred = l_reg.predict(xt_test)
d_pred = d_reg.predict(xt_test)
s_pred = s_reg.predict(xt_test)
p_pred = p_reg.predict(temp)

##Result

In [23]:
from sklearn.metrics import r2_score

In [24]:
r = r2_score(yt_test, r_pred)
l = r2_score(yt_test, l_pred)
d = r2_score(yt_test, d_pred)
s = r2_score(yt_test, s_pred)
p = r2_score(yt_test, p_pred)

In [25]:
print('Random Forest: ' + str(r) + '\nLinear Regression: ' + str(l) + '\nDecision Tree: ' + str(d) + '\nSVR: ' + str(s)  + '\nPolynomial Features: ' + str(p))

Random Forest: 0.46646854963944717
Linear Regression: 0.3792670291925182
Decision Tree: -0.15130921447131707
SVR: 0.37071616688360565
Polynomial Features: 0.31763471384287356


In [26]:
cond = [(data['quality']>=7.5), (data['quality']<7.5)]
gb = ['Good', 'Bad']
data['review'] = np.select(cond, gb)

In [27]:
data

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  review
0               7.4             0.700         0.00  ...      9.4        5     Bad
1               7.8             0.880         0.00  ...      9.8        5     Bad
2               7.8             0.760         0.04  ...      9.8        5     Bad
3              11.2             0.280         0.56  ...      9.8        6     Bad
4               7.4             0.700         0.00  ...      9.4        5     Bad
...             ...               ...          ...  ...      ...      ...     ...
1594            6.2             0.600         0.08  ...     10.5        5     Bad
1595            5.9             0.550         0.10  ...     11.2        6     Bad
1596            6.3             0.510         0.13  ...     11.0        6     Bad
1597            5.9             0.645         0.12  ...     10.2        5     Bad
1598            6.0             0.310         0.47  ...     11.0        6     Bad

[1599 rows x 13 columns]