<a href="https://colab.research.google.com/github/uzair0507/MUF/blob/master/Red_Wine_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

##Separate Features and Target


In [5]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

##Splitting Data into Train and Test sets

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

##Standardization

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()

In [10]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Training on different algorithms


In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [12]:
log_cla = LogisticRegression()
kn_cla = KNeighborsClassifier()
dt_cla = DecisionTreeClassifier()
rf_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [ ]:
log_cla.fit(x_train, y_train)
kn_cla.fit(x_train, y_train)
dt_cla.fit(x_train, y_train)
rf_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

In [14]:
l_pred = log_cla.predict(x_test)
k_pred = kn_cla.predict(x_test)
d_pred = dt_cla.predict(x_test)
r_pred = rf_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [17]:
l_c

array([[  0,   1,   2,   0,   0,   0],
       [  0,   1,   6,   2,   1,   0],
       [  0,   0, 110,  28,   2,   0],
       [  0,   1,  34,  81,   6,   0],
       [  0,   0,   3,  25,  10,   0],
       [  0,   0,   0,   3,   4,   0]])

In [18]:
k_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 0,  1,  5,  3,  1,  0],
       [ 1,  2, 97, 39,  1,  0],
       [ 0,  1, 35, 73, 13,  0],
       [ 0,  0, 10, 11, 17,  0],
       [ 0,  0,  0,  4,  3,  0]])

In [19]:
d_c

array([[  0,   1,   2,   0,   0,   0],
       [  1,   1,   6,   2,   0,   0],
       [  0,   5, 109,  19,   7,   0],
       [  0,   1,  31,  81,   9,   0],
       [  0,   0,   7,   9,  20,   2],
       [  0,   0,   0,   3,   3,   1]])

In [20]:
r_c

array([[  0,   0,   3,   0,   0,   0],
       [  0,   0,   7,   2,   1,   0],
       [  0,   0, 118,  22,   0,   0],
       [  0,   0,  34,  80,   8,   0],
       [  0,   0,   4,  11,  23,   0],
       [  0,   0,   0,   3,   4,   0]])

In [21]:
s_c

array([[  0,   0,   3,   0,   0,   0],
       [  0,   0,   7,   3,   0,   0],
       [  0,   0, 110,  30,   0,   0],
       [  0,   0,  45,  77,   0,   0],
       [  0,   0,   3,  35,   0,   0],
       [  0,   0,   0,   7,   0,   0]])

In [22]:
ks_c

array([[  0,   0,   2,   1,   0,   0],
       [  0,   0,   7,   2,   1,   0],
       [  0,   0, 111,  29,   0,   0],
       [  0,   0,  38,  78,   6,   0],
       [  0,   0,   5,  21,  12,   0],
       [  0,   0,   0,   3,   4,   0]])

##Result

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
log_a = accuracy_score(y_test, l_pred)
kn_a = accuracy_score(y_test, k_pred)
dt_a = accuracy_score(y_test, d_pred)
rf_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [25]:
print('Logistic Regression: ' + str(log_a) + '\nKNN: ' + str(kn_a) + '\nDecision Tree: ' + str(dt_a) + '\nRandom Forest: ' + str(rf_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.63125
KNN: 0.5875
Decision Tree: 0.6625
Random Forest: 0.690625
Linear SVC: 0.584375
Kernel SVC: 0.628125
